# Generated by Django 4.1 on 2022-09-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
